/**
 * @file i18n.h
 * @brief Minimal runtime language switch for the on-device UI.
 *
 * UI strings live in firmware/assets/i18n/{zh-CN,en-US}.json, keyed by a
 * stable English-derived id, and are compiled into i18n_strings.{h,cc}
 * (generated by firmware/scripts/gen_i18n.py -- run it after editing either
 * JSON file). Call sites reference a string via `Tr(StringId::kFoo)`.
 */

#ifndef I18N_H
#define I18N_H

#include <cstdint>

#include "i18n_strings.h"

namespace i18n {

enum class Language : uint8_t {
    kZhCN = 0,
    kEnUS = 1,
};

// Current UI language. Lazily loads the persisted NVS setting on first call.
Language GetLanguage();

// Persists the choice to NVS (key "ui_lang") and updates the in-memory value.
void SetLanguage(Language lang);

// Returns the string for `id` in the current UI language.
const char* Tr(StringId id);

}  // namespace i18n

#endif  // I18N_H
